#############################################################################
# Makefile for building: LabirintEditor
# Generated by qmake (2.01a) (Qt 4.6.0) on: Fri Nov 13 21:26:56 2009
# Project:  LabirintEditor.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile LabirintEditor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=k8 -msse3 -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=k8 -msse3 -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtXml -L/usr/lib64 -L/usr/lib64/qt4 -lQtOpenGL -L/usr/X11R6/lib -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = myglwidget.cpp \
		mainwindow.cpp \
		main.cpp \
		boxmanager.cpp \
		boxcreator.cpp \
		box.cpp \
		point3d.cpp \
		point2d.cpp \
		vertex.cpp \
		AddBoxDialog.cpp \
		ChangeBoxDialog.cpp \
		DeliteBoxDialog.cpp \
		BoxBrokingMatchesDialog.cpp \
		nchangeboxdialog.cpp \
		xmlloader.cpp moc_myglwidget.cpp \
		moc_mainwindow.cpp \
		moc_AddBoxDialog.cpp \
		moc_ChangeBoxDialog.cpp \
		moc_DeliteBoxDialog.cpp \
		moc_BoxBrokingMatchesDialog.cpp \
		moc_nchangeboxdialog.cpp
OBJECTS       = myglwidget.o \
		mainwindow.o \
		main.o \
		boxmanager.o \
		boxcreator.o \
		box.o \
		point3d.o \
		point2d.o \
		vertex.o \
		AddBoxDialog.o \
		ChangeBoxDialog.o \
		DeliteBoxDialog.o \
		BoxBrokingMatchesDialog.o \
		nchangeboxdialog.o \
		xmlloader.o \
		moc_myglwidget.o \
		moc_mainwindow.o \
		moc_AddBoxDialog.o \
		moc_ChangeBoxDialog.o \
		moc_DeliteBoxDialog.o \
		moc_BoxBrokingMatchesDialog.o \
		moc_nchangeboxdialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		LabirintEditor.pro
QMAKE_TARGET  = LabirintEditor
DESTDIR       = 
TARGET        = LabirintEditor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_AddBoxDialog.h ui_ChangeBoxDialog.h ui_DeliteBoxDialog.h ui_BoxBrokingMatchesDialog.h ui_nchangeboxdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LabirintEditor.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtOpenGL.prl \
		/usr/lib64/qt4/libQtGui.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile LabirintEditor.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtOpenGL.prl:
/usr/lib64/qt4/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile LabirintEditor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/LabirintEditor1.0.0 || $(MKDIR) .tmp/LabirintEditor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/LabirintEditor1.0.0/ && $(COPY_FILE) --parents myglwidget.h mainwindow.h boxmanager.h boxcreator.h box.h point3d.h point2d.h vertex.h AddBoxDialog.h ChangeBoxDialog.h DeliteBoxDialog.h BoxBrokingMatchesDialog.h nchangeboxdialog.h xmlloader.h .tmp/LabirintEditor1.0.0/ && $(COPY_FILE) --parents myglwidget.cpp mainwindow.cpp main.cpp boxmanager.cpp boxcreator.cpp box.cpp point3d.cpp point2d.cpp vertex.cpp AddBoxDialog.cpp ChangeBoxDialog.cpp DeliteBoxDialog.cpp BoxBrokingMatchesDialog.cpp nchangeboxdialog.cpp xmlloader.cpp .tmp/LabirintEditor1.0.0/ && $(COPY_FILE) --parents mainwindow.ui AddBoxDialog.ui ChangeBoxDialog.ui DeliteBoxDialog.ui BoxBrokingMatchesDialog.ui nchangeboxdialog.ui .tmp/LabirintEditor1.0.0/ && (cd `dirname .tmp/LabirintEditor1.0.0` && $(TAR) LabirintEditor1.0.0.tar LabirintEditor1.0.0 && $(COMPRESS) LabirintEditor1.0.0.tar) && $(MOVE) `dirname .tmp/LabirintEditor1.0.0`/LabirintEditor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/LabirintEditor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_myglwidget.cpp moc_mainwindow.cpp moc_AddBoxDialog.cpp moc_ChangeBoxDialog.cpp moc_DeliteBoxDialog.cpp moc_BoxBrokingMatchesDialog.cpp moc_nchangeboxdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_myglwidget.cpp moc_mainwindow.cpp moc_AddBoxDialog.cpp moc_ChangeBoxDialog.cpp moc_DeliteBoxDialog.cpp moc_BoxBrokingMatchesDialog.cpp moc_nchangeboxdialog.cpp
moc_myglwidget.cpp: point3d.h \
		boxcreator.h \
		vertex.h \
		point2d.h \
		box.h \
		boxmanager.h \
		myglwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) myglwidget.h -o moc_myglwidget.cpp

moc_mainwindow.cpp: myglwidget.h \
		point3d.h \
		boxcreator.h \
		vertex.h \
		point2d.h \
		box.h \
		boxmanager.h \
		xmlloader.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_AddBoxDialog.cpp: boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h \
		AddBoxDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) AddBoxDialog.h -o moc_AddBoxDialog.cpp

moc_ChangeBoxDialog.cpp: boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h \
		ChangeBoxDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ChangeBoxDialog.h -o moc_ChangeBoxDialog.cpp

moc_DeliteBoxDialog.cpp: boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h \
		DeliteBoxDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) DeliteBoxDialog.h -o moc_DeliteBoxDialog.cpp

moc_BoxBrokingMatchesDialog.cpp: BoxBrokingMatchesDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) BoxBrokingMatchesDialog.h -o moc_BoxBrokingMatchesDialog.cpp

moc_nchangeboxdialog.cpp: ChangeBoxDialog.h \
		boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h \
		nchangeboxdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) nchangeboxdialog.h -o moc_nchangeboxdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_AddBoxDialog.h ui_ChangeBoxDialog.h ui_DeliteBoxDialog.h ui_BoxBrokingMatchesDialog.h ui_nchangeboxdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_AddBoxDialog.h ui_ChangeBoxDialog.h ui_DeliteBoxDialog.h ui_BoxBrokingMatchesDialog.h ui_nchangeboxdialog.h
ui_mainwindow.h: mainwindow.ui \
		myglwidget.h \
		point3d.h \
		boxcreator.h \
		vertex.h \
		point2d.h \
		box.h \
		boxmanager.h
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_AddBoxDialog.h: AddBoxDialog.ui
	/usr/bin/uic AddBoxDialog.ui -o ui_AddBoxDialog.h

ui_ChangeBoxDialog.h: ChangeBoxDialog.ui
	/usr/bin/uic ChangeBoxDialog.ui -o ui_ChangeBoxDialog.h

ui_DeliteBoxDialog.h: DeliteBoxDialog.ui
	/usr/bin/uic DeliteBoxDialog.ui -o ui_DeliteBoxDialog.h

ui_BoxBrokingMatchesDialog.h: BoxBrokingMatchesDialog.ui
	/usr/bin/uic BoxBrokingMatchesDialog.ui -o ui_BoxBrokingMatchesDialog.h

ui_nchangeboxdialog.h: nchangeboxdialog.ui
	/usr/bin/uic nchangeboxdialog.ui -o ui_nchangeboxdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

myglwidget.o: myglwidget.cpp myglwidget.h \
		point3d.h \
		boxcreator.h \
		vertex.h \
		point2d.h \
		box.h \
		boxmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myglwidget.o myglwidget.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		myglwidget.h \
		point3d.h \
		boxcreator.h \
		vertex.h \
		point2d.h \
		box.h \
		boxmanager.h \
		xmlloader.h \
		ui_mainwindow.h \
		AddBoxDialog.h \
		DeliteBoxDialog.h \
		ChangeBoxDialog.h \
		BoxBrokingMatchesDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

main.o: main.cpp mainwindow.h \
		myglwidget.h \
		point3d.h \
		boxcreator.h \
		vertex.h \
		point2d.h \
		box.h \
		boxmanager.h \
		xmlloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

boxmanager.o: boxmanager.cpp boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boxmanager.o boxmanager.cpp

boxcreator.o: boxcreator.cpp boxcreator.h \
		point3d.h \
		vertex.h \
		point2d.h \
		box.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boxcreator.o boxcreator.cpp

box.o: box.cpp box.h \
		point3d.h \
		vertex.h \
		point2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o box.o box.cpp

point3d.o: point3d.cpp point3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point3d.o point3d.cpp

point2d.o: point2d.cpp point2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point2d.o point2d.cpp

vertex.o: vertex.cpp vertex.h \
		point3d.h \
		point2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vertex.o vertex.cpp

AddBoxDialog.o: AddBoxDialog.cpp AddBoxDialog.h \
		boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h \
		ui_AddBoxDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddBoxDialog.o AddBoxDialog.cpp

ChangeBoxDialog.o: ChangeBoxDialog.cpp ChangeBoxDialog.h \
		boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h \
		ui_ChangeBoxDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChangeBoxDialog.o ChangeBoxDialog.cpp

DeliteBoxDialog.o: DeliteBoxDialog.cpp DeliteBoxDialog.h \
		boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h \
		ui_DeliteBoxDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeliteBoxDialog.o DeliteBoxDialog.cpp

BoxBrokingMatchesDialog.o: BoxBrokingMatchesDialog.cpp BoxBrokingMatchesDialog.h \
		ui_BoxBrokingMatchesDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BoxBrokingMatchesDialog.o BoxBrokingMatchesDialog.cpp

nchangeboxdialog.o: nchangeboxdialog.cpp nchangeboxdialog.h \
		ChangeBoxDialog.h \
		boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h \
		ui_nchangeboxdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nchangeboxdialog.o nchangeboxdialog.cpp

xmlloader.o: xmlloader.cpp xmlloader.h \
		boxmanager.h \
		box.h \
		point3d.h \
		vertex.h \
		point2d.h \
		boxcreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlloader.o xmlloader.cpp

moc_myglwidget.o: moc_myglwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myglwidget.o moc_myglwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_AddBoxDialog.o: moc_AddBoxDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddBoxDialog.o moc_AddBoxDialog.cpp

moc_ChangeBoxDialog.o: moc_ChangeBoxDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ChangeBoxDialog.o moc_ChangeBoxDialog.cpp

moc_DeliteBoxDialog.o: moc_DeliteBoxDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DeliteBoxDialog.o moc_DeliteBoxDialog.cpp

moc_BoxBrokingMatchesDialog.o: moc_BoxBrokingMatchesDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BoxBrokingMatchesDialog.o moc_BoxBrokingMatchesDialog.cpp

moc_nchangeboxdialog.o: moc_nchangeboxdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nchangeboxdialog.o moc_nchangeboxdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

